import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";

import { auth } from "@/auth";
import { cn } from "@/lib/utils";
import { Navbar } from "@/components/navbar";
import { CSPostHogProvider } from "@/components/posthog-provider";
import { IdentificationTracker } from "@/components/identification-tracker";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <CSPostHogProvider>
          <body className={cn("min-h-screen", inter.className)}>
            <Navbar />
            <IdentificationTracker />
            {children}
          </body>
        </CSPostHogProvider>
      </html>
    </SessionProvider>
  );
}
